env:
 databaseName: "IHCLE2EDataBase"
 connectionString : "mongodb://ihcle2e:X84dtG7xB43lW8iyP7AtzZS5SwzWEYujn4G3EGoZZGnJtRegGUBdXMYlehAwG2qVuWXUvxKew4HeACDbDWwkLg==@ihcle2e.mongo.cosmos.azure.com:10255/?ssl=true&retrywrites=false&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@ihcle2e@"
 PAYMENT_SERVICE_HOST: "http://ihcl-paymentservice:8083"
 LOYALTY_SERVICE_HOST: "http://ihcl-loyalty:8084"
 HUDINI_SERVICE_HOST: "https://api-e2ev2.tajhotels.com/hudiniService"
 SSO_SERVICE_HOST: "http://ihcl-sso:3001"
 CART_SERVICE_HOST: "http://ihcl-cartservice:8081"
 SANITY_HOST: "https://ocl5w36p.api.sanity.io/v2022-03-07/data/query/preprod"
 memberShipPlanURL: "https://api-e2ev2.tajhotels.com/loyaltyService/v1/gravty/entity-data/members/membership_plan/"
 memberLookupValidationURL: "https://api-e2ev2.tajhotels.com/loyaltyService/v1/gravty/members/list/?mobile"
 memberEnrollmentURL: "https://api-e2ev2.tajhotels.com/loyaltyService/v1/gravty/members"
 orderIdBooking : "EWeb"
 orderIdEpicure : "EEpic"
 orderIdTEGC : "ETEGC"
 redisKey: "vzaLORNA7cO9HjIDYg32CTqElV6CzGziDAzCaGRlwCY"
 redisHost: "app-dev-redis.redis.cache.windows.net"
 redisPort: "6380"
 pastBookings: "1"
 upcomingBookings: "1"
 nonDepositRoomCommitBooking: "1"
 timeSecondsOfTTL: 600
 membershipSource: "selected"
 requestTimeoutMillis: "120000"
 connectionPoolMinSize: 200
 connectionPoolMaxSize: 200
 bookingRetryCount: 3
 pendingBookingsForDuration: 30
 tenMinAgoPendingOrders: 10
 twoDaysAgoPendingOrders: 2

 dataEncryptionAndDecryptionKey: "1a2b3c4d5e6f7g8h"
 twoMinAgoPendingOrders : 2
cron:
  ordercron: true
  api_ordercron: "http://ihcl-orderservice:8086/v1/orders/update-processing-gc"
  updateconfirmorder: true
  api_updateconfirmorder: "http://ihcl-orderservice:8086/v1/orders/update-confirm-order"
  tegcepciurecron: true
  api_tegcepciurecron: "http://ihcl-orderservice:8086/v1/orders/cron-tegc-epicure"
