env:
 databaseName: "IHCLSITDataBase"
 connectionString : "mongodb://ihclsit:tmBXKavuBiNYle6GEdHoEIeVjprZN6dk7Hes4GBOoYu2Lguk7cQwXgkPAQM2HXiJ2uqOHD4LmsYWACDbgxGFyw==@ihclsit.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@ihclsit@"
 PAYMENT_SERVICE_HOST: "http://ihcl-paymentservice:8083"
 LOYALTY_SERVICE_HOST: "http://ihcl-loyalty:8084"
 HUDINI_SERVICE_HOST: "http://ihcl-hudiniservice:8085"
 SSO_SERVICE_HOST: "http://ihcl-sso:3001"
 CART_SERVICE_HOST: "http://ihcl-cartservice:8081"
 SANITY_HOST: "https://ocl5w36p.api.sanity.io/v2022-03-07/data/query/dev"
 memberShipPlanURL: "https://api-qa1v2.tajhotels.com/loyaltyService/v1/gravty/entity-data/members/membership_plan/"
 memberLookupValidationURL: "https://api-qa1v2.tajhotels.com/loyaltyService/v1/gravty/members/list/?mobile"
 memberEnrollmentURL: "https://api-qa1v2.tajhotels.com/loyaltyService/v1/gravty/members"
 orderIdBooking : "SWeb"
 orderIdEpicure : "SEpic"
 orderIdTEGC : "STEGC"
 redisKey: "vzaLORNA7cO9HjIDYg32CTqElV6CzGziDAzCaGRlwCY"
 redisHost: "app-dev-redis.redis.cache.windows.net"
 redisPort: "6380"
 pastBookings: "1"
 upcomingBookings: "1"
 nonDepositRoomCommitBooking: "1"
 timeSecondsOfTTL: 600
 membershipSource: "selected"
 requestTimeoutMillis: "120000"
 connectionPoolMinSize: 200
 connectionPoolMaxSize: 200
 bookingRetryCount: 3
 pendingBookingsForDuration: 30
 tenMinAgoPendingOrders: 10
 twoDaysAgoPendingOrders: 2
 dataEncryptionAndDecryptionKey: "1a2b3c4d5e6f7g8h"
 twoMinAgoPendingOrders : 2

cron:
  ordercron: true
  api_ordercron: "http://ihcl-orderservice:8086/v1/orders/update-processing-gc"
  updateconfirmorder: true
  api_updateconfirmorder: "http://ihcl-orderservice:8086/v1/orders/update-confirm-order"
  tegcepciurecron: true
  api_tegcepciurecron: "http://ihcl-orderservice:8086/v1/orders/cron-tegc-epicure"
