env:
 databaseName: "IHCLUATDataBase"
 connectionString : "mongodb://ihcluat:LbAgFmOKkyPZsHiMJO9yfDYDkyYKR5gsIqt8IKdU4HDQrtpsWRssDdRHIdrfEZLj2t9HuLPDGW3lACDbPGJtqw==@ihcluat.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@ihcluat"
 PAYMENT_SERVICE_HOST: "http://ihcl-paymentservice:8083"
 LOYALTY_SERVICE_HOST: "http://ihcl-loyalty:8084"
 HUDINI_SERVICE_HOST: "http://ihcl-hudiniservice:8085"
 SSO_SERVICE_HOST: "http://ihcl-sso:3001"
 CART_SERVICE_HOST: "http://ihcl-cartservice:8081"
 SANITY_HOST: "https://ocl5w36p.api.sanity.io/v2022-03-07/data/query/integrateduat"
 memberShipPlanURL: "http://ihcl-loyalty:8084/v1/gravty/entity-data/members/membership_plan/"
 memberLookupValidationURL: "http://ihcl-loyalty:8084/v1/gravty/members/list/?mobile"
 memberEnrollmentURL: "http://ihcl-loyalty:8084/v1/gravty/members"
 orderIdBooking : "UWeb"
 orderIdEpicure : "UEpic"
 orderIdTEGC : "UTEGC"
 redisKey: "vzaLORNA7cO9HjIDYg32CTqElV6CzGziDAzCaGRlwCY"
 redisHost: "app-dev-redis.redis.cache.windows.net"
 redisPort: "6380"
 pastBookings: "1"
 upcomingBookings: "1"
 nonDepositRoomCommitBooking: "1"
 timeSecondsOfTTL: 600
 membershipSource: "selected"
 requestTimeoutMillis: "120000"
 connectionPoolMinSize: 200
 connectionPoolMaxSize: 200
 bookingRetryCount: 3
 pendingBookingsForDuration: 30
 tenMinAgoPendingOrders: 10
 twoDaysAgoPendingOrders: 2

 dataEncryptionAndDecryptionKey: "1a2b3c4d5e6f7g8h"
 twoMinAgoPendingOrders : 2
 APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=4754bffe-22da-4c66-b893-b426d8b63c5d;IngestionEndpoint=https://centralindia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://centralindia.livediagnostics.monitor.azure.com/;ApplicationId=ee8f6d66-6882-4db2-b1cc-2a2929bb1184"
cron:
  ordercron: true
  api_ordercron: "http://ihcl-orderservice:8086/v1/orders/update-processing-gc"
  updateconfirmorder: true
  api_updateconfirmorder: "http://ihcl-orderservice:8086/v1/orders/update-confirm-order"
  tegcepciurecron: true
  api_tegcepciurecron: "http://ihcl-orderservice:8086/v1/orders/cron-tegc-epicure"
