package com.ihcl.order.utils

const val CLIENT_UNAVAILABLE_ERR_MSG="client is unavailable"
const val SOMETHING_WENT_WRONG_ERR_MSG="Something went wrong"
const val ORDER_NOT_FOUND_FAILED_ERR_MSG="Order not found"
const val PRE_AUTH_CANCEL_FAILED_ERR_MSG="Reserved amount back to gift card failed"
const val SERIALIZE_ERR_MSG="Unable to serialize client response"
const val INVALID_REQUEST_STRUCTURE_ERR_MSG="Invalid request structure"
const val ORDER_ID_REQUIRED_ERR_MSG = "OrderId is required"
const val MISSING_ORDER_ID_AND_EMAIL_ERROR_MSG = "Both order ID and email are required."
const val CUSTOMERHASH_REQUIRED_ERR_MSG = "CustomerHash is required"
const val USER_EXISTS = "Member is already exists..."
const val TIME_OUT = "Time out issue"
const val GRAVTY_VOUCHER_NOT_FOUND = "No vouchers found for the user.."
const val BOOKINGS_NOT_FOUND = "Your booking could not be found. Please check the information you have entered."
const val EMPTY_CART_ERR_MSG= "Cart is empty"
const val CONFIRM_BOOKING_ERR_MSG= "Confirm booking not allowed"
const val ORDER_ID_AND_CUSTOMER_HASH_ERR_MSG= "orderId or customerHash must not be null or empty"
const val VOUCHER_REDEMPTION_FAILED_ERR_MSG= "Voucher redemption failed"
const val BUY_GIFT_CARD_FAILED_ERR_MSG= "BuyGC failed"
